name: amz-aws-cli
base: core22
summary: Universal Command Line Interface for Amazon Web Services - strictly confined
description: |
  Universal Command Line Interface for Amazon Web Services

  This is a strictly confined version, for enhanced security.

  The AWS Command Line Interface (CLI) is a unified tool to
  manage your AWS services. With just one tool to download
  and configure, you can control multiple AWS services from
  the command line and automate them through scripts.

  The AWS CLI v2 offers several new features including improved
  installers, new configuration options such as AWS Single Sign-On (SSO),
  and various interactive features. 

  For best user experience, create an alias for this snap to the standard upstream binary name.
  $ sudo snap alias amz-aws-cli aws

  If you are migrating from other packaging of AWS CLI, you may want to migrate your existing config.
  $ amz-aws-cli.setup

  If you find bash completion is not working, you can probably get it working by install the core snap.
  This seems to be a bug in the completion implementation.
  $ sudo snap install core
confinement: strict
grade: stable
adopt-info: aws
architectures:
  - amd64
source-code: https://github.com/nysasounds/amz-aws-cli
issues: https://github.com/nysasounds/amz-aws-cli/issues

apps:
  amz-aws-cli:
    command: bin/aws
    environment:
      GROFF_FONT_PATH: "$SNAP/usr/share/groff/current/font"
      GROFF_TMAC_PATH: "$SNAP/usr/share/groff/current/tmac"
    completer: bin/aws_completion.bash
    plugs:
      - network
      - network-bind
      - home
      - desktop
  setup:
    command: bin/setup
    plugs:
      - dot-aws

plugs:
  dot-aws:
    interface: personal-files
    read:
    - $HOME/.aws

parts:
  aws:
    plugin: nil
    source: https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.27.31.zip
    source-type: zip
    override-build: |
      $CRAFT_PART_BUILD/aws/install -i $CRAFT_PART_INSTALL/aws
      VER_SYM=$(readlink -f $CRAFT_PART_INSTALL/aws/v2/current)
      VER=$(basename $VER_SYM)
      mkdir -p $CRAFT_PART_INSTALL/bin
      ln -s ../aws/v2/$VER/bin/aws $CRAFT_PART_INSTALL/bin/
      ln -s ../aws/v2/$VER/bin/aws_completer $CRAFT_PART_INSTALL/bin/
      rm $CRAFT_PART_INSTALL/aws/v2/current
      craftctl default
      craftctl set version=$VER
    stage-packages:
      - groff-base # Required for help
  utils:
    plugin: dump
    source: utils
    organize:
      aws_completion.bash: bin/aws_completion.bash
      setup: bin/setup
    after:
      - aws
